server:
  port: 8082

spring:
  application:
    name: datastore-service
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/messagesdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    ru.chess: DEBUG
    org.hibernate.SQL: DEBUG